### ISSUE TITLE
Tasks are being limited based on width

### ISSUE THREAD

**Issue by uri** [blindFS/vim-taskwarrior#117]
I have

    let g:task_rc_override = 'rc.defaultwidth=0'

and running `:TW` shows 13 tasks but running `task next` in my shell correctly produced 18 tasks. Removing the option for width and the running `:TW` produces 6 tasks.

**Comment by logorrhea** [comment]
I had to use the height override rather than the width.
Try `let g:task_rc_override = 'rc.defaultheight=0'` instead.

**Comment by blindFS** [comment]
Fixed now.

**Comment by uri** [comment]
@blindFS is this fixed based on a commit or based on @logorrhea's comment?

**Comment by logorrhea** [comment]
@uri Looks like [c37ed61](https://github.com/blindFS/vim-taskwarrior/commit/c37ed61fc2a30284d7538ebad7a33fbea530ec90) sets `rc.defaultheight=0` by default now?
